version: '2.0'

volumes:
  odoo-data:
    driver: local
  odoo-config:
    driver: local
  pg10data12:
    driver: local

services:
  pg10-odoo12:
    image: postgres:10.1
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    ports:
      - "5433:5432"
    volumes:
      - pg10data12:/var/lib/postgresql/pgdata
  odoo10-ww:
    tty: true
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - PASSWORD=odoo
      - USER=odoo
      - HOST=pg10-odoo12
    depends_on:
      - pg10-odoo12
    ports:
      - "8069:8069"
      - "3000:3000"
    volumes:
      - ./:/mnt/extra-addons
      - odoo-data:/var/lib/odoo
      - odoo-config:/etc/odoo

    command: odoo --limit-time-real=300000
